import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Template from "@/app/component/Template";

import Header from "@/app/component/UI/header"; // ✅ Capital H
import Footer from "@/app/component/UI/Footer"; // ✅ Capital F

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon-light.svg',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <Providers>
          <Template>
            <Header />
            {children}
                  <Footer />
          </Template>
        </Providers>
      </body>
    </html>
  );
}
